### ISSUE TITLE
Parse media type parameters

### ISSUE THREAD

**Issue by tobyzerner** [pattisahusiwa/http-accept#6]
Currently parameters are not parsed into key/value pairs, they're just stored as an array of strings:

```php
$mediaList = (new AcceptParser())->parse('*/*; one=value; two=value');
print_r($mediaList->preferedMedia(0)->parameters());
```

```
Array
(
    [0] => one=value,
    [1] => two=value
)
```

Is there any reason they're not parsed into key/value pairs, ie:

```
Array
(
    [one] => value,
    [two] => value
)
```

**Comment by pattisahusiwa** [comment]
I can add the feature. However, currently, I've no idea the real use case of the feature. Can you give some real example?

**Comment by tobyzerner** [comment]
Basically to just cut out a step in reading media type parameter keys and values. My real-world use-case is parsing the parameters in the [JSON:API media type](https://jsonapi.org/format/1.1/#jsonapi-media-type):

```php
$mediaList = (new AcceptParser())->parse($acceptHeader);

$count = $mediaList->count();
for ($i = 0; $i < $count; $i++) {
    $mediaType = $mediaList->preferredMedia($i);

    if (! in_array($mediaType->mimetype(), [JsonApi::MEDIA_TYPE, '*/*'])) {
        continue;
    }

    $parameters = $mediaType->parameters();

    // invalid if there are any parameters other than ext/profile
    if (! empty(array_diff(array_keys($parameters), ['ext', 'profile']))) {
        continue;
    }

    // invalid if there are any unsupported extensions
    $extensionUris = isset($parameters['ext']) ? explode(' ', $parameters['ext']) : [];
    if (! empty(array_diff($extensionUris, array_keys($this->extensions)))) {
        continue;
    }

    return $extensionUris;
}

// my current substitute:
function parseParameters(array $parameters): array
{
    return array_reduce($parameters, function ($a, $v) {
        $parts = explode('=', $v, 2);
        $a[$parts[0]] = trim($parts[1], '"');
        return $a;
    }, []);
}
```

**Comment by pattisahusiwa** [comment]
Please check the latest commit.

**Comment by tobyzerner** [comment]
Great thanks @pattisahusiwa! Looks good, just a couple of questions:

1. Any reason you've gone with `parameter` singular instead of plural? Plural seems a bit more logical to me, since the instance contains all parameters, not just one individual parameter:

```php
$media->parameters()->count();
$media->parameters()->get('level');
```

2. Can we stripe quotes off either end of parameter values when parsing? It is specified in various [RFCs](https://datatracker.ietf.org/doc/html/rfc2045#section-5.1):

> Note that the value of a quoted string parameter does not include the
   quotes.  That is, the quotation marks in a quoted-string are not a
   part of the value of the parameter, but are merely used to delimit
   that parameter value.

So it'd be nice for it to work like this:

```php
$mediaList = (new AcceptParser())->parse('application/json; ext="parameter value"');
$media = $mediaList->preferredMedia(0);
$media->parameters()->get('ext'); // => parameter value
```

**Comment by pattisahusiwa** [comment]
Thanks, I'll fix the issues.

**Comment by pattisahusiwa** [comment]
Usually, I use plural name when return an array. Because the function return one object, I choose to use singular name. The plural function goes to `Parameter` class when we need to retrieve all parameters. For example,
```php
$media->parameter()->values();
```

**Comment by tobyzerner** [comment]
Right, but wouldn't the name `Parameters` be more suitable for the class itself, because it contains multiple key-value pairs, as opposed to a `Parameter` class which should represent a single parameter?

```php
new Parameters($keyValuePairs);
new Parameter($key, $value);
```

You can see a similar naming pattern in other codebases, like [Symfony's Request class](https://symfony.com/doc/current/components/http_foundation.html#accessing-request-data), which has plural properties like `cookies`, `attributes`, and `headers` referring to `ParameterBag` instances.

**Comment by tobyzerner** [comment]
Also, an `all()` method to get an array of all parameters would be fantastic:

```php
$parameters->all(); // ['key1' => 'value1', 'key2' => 'value2']
```

**Comment by pattisahusiwa** [comment]
Thank you @tobyzerner, you check the latest commits.

**Comment by tobyzerner** [comment]
Thanks for that @pattisahusiwa, greatly appreciated!

I have one last request: can you please tag a version so I can depend on this in [json-api-server](https://github.com/tobyzerner/json-api-server)?
